// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AvatarController from "./avatar_controller"
application.register("avatar", AvatarController)

import FormChangesController from "./form_changes_controller"
application.register("form-changes", FormChangesController)

import InfiniteScrollController from "./infinite_scroll_controller"
application.register("infinite-scroll", InfiniteScrollController)

import MapController from "./map_controller"
application.register("map", MapController)

import PasswordValidationController from "./password_validation_controller"
application.register("password-validation", PasswordValidationController)

import PhoneFormatController from "./phone_format_controller"
application.register("phone-format", PhoneFormatController)

import PhoneNumberChangeController from "./phone_number_change_controller"
application.register("phone-number-change", PhoneNumberChangeController)

import ProfileDropdownController from "./profile_dropdown_controller"
application.register("profile-dropdown", ProfileDropdownController)
