default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DB_USERNAME") { 'postgres' }%>
  password: <%= ENV.fetch("DB_PASSWORD") { 'postgres'} %>
  host: <%= ENV.fetch("DB_HOST") {'127.0.0.1'} %>
  database: <%= ENV.fetch("DB_NAME") {'baitmate_development'} %>
  port: <%= ENV.fetch("DB_PORT") { 5432 } %>
  timeout: 5000
test:
  <<: *default
development:
  <<: *default
staging:
  <<: *default
production:
  <<: *default